### ISSUE TITLE
tester@Test:~/nginx-installer$ sudo ./install-nginx.sh 1.18.0

### ISSUE THREAD

**Issue by padma-lakshmi** [oohnoitz/nginx-installer#5]
tester@Test:~/nginx-installer$ sudo ./install-nginx.sh 1.18.0
Downloading: nginx-1.18.0 ...   [DONE]
Extracting:  nginx-1.18.0 ...   [DONE]
Applying Patch: *
./install-nginx.sh: line 58: patches/*: No such file or directory
Configuring... --with-debug --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --add-module=modules/ngx_rtmp
checking for OS
 + Linux 4.15.0-101-generic x86_64
checking for C compiler ... not found

./configure: error: C compiler cc is not found

Compiling...
make: *** No rule to make target 'build', needed by 'default'.  Stop.
Installing...
make: *** No rule to make target 'install'.  Stop.
Finished!
tester@Test:~/nginx-installer$

installation is not successful.

_Originally posted by @padma-lakshmi in https://github.com/oohnoitz/nginx-installer/issues/4#issuecomment-645601200_

**Comment by padma-lakshmi** [comment]
installed compiler by this command
sudo apt-get install gcc

after that again run the command 
sudo ./install-nginx.sh 1.18.0

but not successful.

**Comment by padma-lakshmi** [comment]
![image](https://user-images.githubusercontent.com/58339401/84946867-f665ac80-b106-11ea-99ef-3c6fc6304788.png)

**Comment by padma-lakshmi** [comment]
![image](https://user-images.githubusercontent.com/58339401/84947096-4a709100-b107-11ea-9fc5-1b856f3ab4e2.png)

**Comment by oohnoitz** [comment]
The error is because you are still missing some build dependencies. For Debian, you will need the following to compile nginx: `git-core wget gcc libc-dev make libpcre3-dev libssl-dev zlib1g-dev` or the equivalent for any other distribution.

Going to close this since the error isn't due to the bash scripts themselves. The `install-nginx` script is primarily used to help generate the arguments needed for `./configure` before doing `make && make install`.
